title: Nitish Singla # your name (or website title) here
logo: "/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Senior Backend Engineer
  <br><br>
  <a href="mailto:aashima.ahuja811@gmail.com">nsingla85@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/nitish-singla-69175969/">LinkedIn Profile</a>
  <br>
  <a href="https://www.gihub.com/nitishsingla91/">Gihub</a> 
theme: jekyll-theme-minimal
