title: Nitish Singla # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Senior Java Backend Engineer with Cloud and Microservices Architecture
  <br><br>
  <a href="mailto:nsingla85@yahoo.com">nsingla85@yahoo.com </a>
  <br>
  <a href="https://www.linkedin.com/in/nitish-singla-69175969/">LinkedIn Profile</a>
  <br>
  <a href="https://github.com/nitishsingla91">Gihub</a> 
theme: jekyll-theme-minimal
